package com.honor.mybatis.entity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_resource
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Resource {
    /**
     * Database Column Remarks:
     *   资源 ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resource.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   资源名称,一般是中文名称(给人看的)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resource.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * Database Column Remarks:
     *   资源权限字符串,一般是 Shiro 默认的通配符表示(给人看的)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resource.permission
     *
     * @mbg.generated
     */
    private String permission;

    /**
     * Database Column Remarks:
     *   资源 url 表示,我们设计的系统让 Shiro 通过这个路径字符串去匹配浏览器中显示的路径
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resource.url
     *
     * @mbg.generated
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resource.parent_id
     *
     * @mbg.generated
     */
    private Integer parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resource.icon
     *
     * @mbg.generated
     */
    private String icon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resource.type
     *
     * @mbg.generated
     */
    private Integer type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resource.id
     *
     * @return the value of t_resource.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resource.id
     *
     * @param id the value for t_resource.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resource.name
     *
     * @return the value of t_resource.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resource.name
     *
     * @param name the value for t_resource.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resource.permission
     *
     * @return the value of t_resource.permission
     *
     * @mbg.generated
     */
    public String getPermission() {
        return permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resource.permission
     *
     * @param permission the value for t_resource.permission
     *
     * @mbg.generated
     */
    public void setPermission(String permission) {
        this.permission = permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resource.url
     *
     * @return the value of t_resource.url
     *
     * @mbg.generated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resource.url
     *
     * @param url the value for t_resource.url
     *
     * @mbg.generated
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resource.parent_id
     *
     * @return the value of t_resource.parent_id
     *
     * @mbg.generated
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resource.parent_id
     *
     * @param parentId the value for t_resource.parent_id
     *
     * @mbg.generated
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resource.icon
     *
     * @return the value of t_resource.icon
     *
     * @mbg.generated
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resource.icon
     *
     * @param icon the value for t_resource.icon
     *
     * @mbg.generated
     */
    public void setIcon(String icon) {
        this.icon = icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resource.type
     *
     * @return the value of t_resource.type
     *
     * @mbg.generated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resource.type
     *
     * @param type the value for t_resource.type
     *
     * @mbg.generated
     */
    public void setType(Integer type) {
        this.type = type;
    }
}