package com.honor.mybatis.entity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_role_resource
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class RoleResource {
    /**
     * Database Column Remarks:
     *   角色资源关联 ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_resource.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   角色 id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_resource.role_id
     *
     * @mbg.generated
     */
    private Integer roleId;

    /**
     * Database Column Remarks:
     *   资源 id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_resource.resource_id
     *
     * @mbg.generated
     */
    private Integer resourceId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role_resource.id
     *
     * @return the value of t_role_resource.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role_resource.id
     *
     * @param id the value for t_role_resource.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role_resource.role_id
     *
     * @return the value of t_role_resource.role_id
     *
     * @mbg.generated
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role_resource.role_id
     *
     * @param roleId the value for t_role_resource.role_id
     *
     * @mbg.generated
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role_resource.resource_id
     *
     * @return the value of t_role_resource.resource_id
     *
     * @mbg.generated
     */
    public Integer getResourceId() {
        return resourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role_resource.resource_id
     *
     * @param resourceId the value for t_role_resource.resource_id
     *
     * @mbg.generated
     */
    public void setResourceId(Integer resourceId) {
        this.resourceId = resourceId;
    }
}