package com.honor.mybatis.mapper;

import com.honor.mybatis.entity.RoleResource;
import java.util.List;

public interface RoleResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_resource
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_resource
     *
     * @mbg.generated
     */
    int insert(RoleResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_resource
     *
     * @mbg.generated
     */
    RoleResource selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_resource
     *
     * @mbg.generated
     */
    List<RoleResource> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_resource
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(RoleResource record);
}